### ISSUE TITLE
how to prove the webrtc-swarm do it work?

### ISSUE THREAD

**Issue by hfmanly** [mafintosh/webrtc-swarm#1]
I have installed wrtc, webbrt-swarm,and all the dependent npm packages  in Ubuntu 14.10
and execute: 
root@ubuntu:/home/hf/hfnj/node-v0.12.3-linux-x64/bin/node_modules/webrtc-swarm# node example.js

but how I know that the webbrt-swarm is working and how to prove it ?

Thanks

BTW
uname -a
Linux ubuntu 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mafintosh** [comment]
Try trying again with the latest version of signalhub (4.1.1) which fixes some bugs that might be related to this.
