### ISSUE TITLE
possible to pass config options to constructed RTCDataChannels?

### ISSUE THREAD

**Issue by mreinstein** [mafintosh/webrtc-swarm#16]
in `simple-peer` (the underlying webrtc module) it's possible to pass options for the RTCDataChannels that get constructed, like this:

``` javascript
const SimplePeer = require('simple-peer');

const config = {
  trickle: false,
  iceServers: [ { url: 'stun:stun.l.google.com:19302' } ],
  // configure the data channels to behave like UDP for maximum performance
  channelConfig: { reliable: false, maxRetransmits: 0, ordered: false },
  ...
};

let p = new Peer(config);
```

Is there any way to do this in `webrtc-swarm` ? the default settings produce RTCDataChannels that are reliable, ordered, and attempt packet retransmission. I need to shut this stuff off to get more UDP like behavior for my real-time game.

thanks for a great module btw! 👍

**Comment by perguth** [comment]
Nice! Extend `opts` like here https://github.com/mafintosh/webrtc-swarm/pull/15 and file a pull request.

**Comment by mreinstein** [comment]
@pguth thanks for the pointer; I'll send a PR shortly.

btw, The README has this blurb:

> Valid keys for opts include: wrtc, uid, maxPeers

but looking at the code sample from #15  it seems there are other options that can be passed in (this.config, this.stream, this.offerConstraints, ...) Should these be documented in the README?

**Comment by mreinstein** [comment]
ok I've answered my own question. It looks like these are options that are passed through directly to the underlying `simple-peer` instances. I'll tweak the README and send along with my PR.
