### ISSUE TITLE
doesn't fully connect > 2 peers

### ISSUE THREAD

**Issue by mreinstein** [mafintosh/webrtc-swarm#18]
my script:

``` javascript
var swarm = require('webrtc-swarm')
var signalhub = require('signalhub')

var hub = signalhub('swarm-example', ['http://localhost:8000'])

var sw = swarm(hub)

sw.on('peer', function (peer, id) {
  console.log('connected to a new peer:', id)
  console.log('total peers:', sw.peers.length)
})

sw.on('disconnect', function (peer, id) {
  console.log('disconnected from a peer:', id)
  console.log('total peers:', sw.peers.length)
})
```

this is browserified and served up in latest chrome. I also have signalhub running locally with the command:

``` bash
signalhub listen -p 8000
```

I open 3 browser windows to the test script from above. the first 2 connect. The 3rd doesn't.

**Comment by lukeburns** [comment]
Just added a test to check for this, but it's passing fine. That said, I am having exactly the same issue in browser (Chrome 52).

**Comment by lukeburns** [comment]
I cannot connect to more than two local peers, but I'm having no trouble connecting to more than two remote peers.

**Comment by perguth** [comment]
Yes, that happens. I can't tell you why but just open your third and fourth tab using the browsers incognito mode. Then it will work. Please confirm.

**Comment by mreinstein** [comment]
@pguth I've confirmed that is the case for me (chrome 53.) Opening tabs in incognito mode solves the problem. It would probably be good to leave this issue open since it's technically a bug. Not sure if it's in signalhub or webrtc-swarm.

I'll send a PR with a note in the README about this current limitation.

**Comment by perguth** [comment]
@mreinstein Thanks 🎆! But I close since it's outside the scope of `webrtc-swarm` (technically and practically). For the purpose of bouncing information between tabs maybe give [page-bus](https://github.com/substack/page-bus) a try.

> I'll send a PR with a note in the README about this current limitation.

💯

**Comment by mreinstein** [comment]
@pguth if we aren't sure what is causing this limitation, how do we know that this isn't something caused by the way `webrtc-swarm` interacts with the underlying `signalhub` instance? We don't know if this is a bug in this module, or upstream. Closing the issue hides it.

> For the purpose of bouncing information between tabs maybe give page-bus a try.

cool module! 👍

**Comment by perguth** [comment]
I strongly suspect this to be a browser limitation. I find the interaction between those two modules quite clear. But if you find out more please let us know. :eyes:

**Comment by mreinstein** [comment]
@pguth I just tried signalhub with 3 local connections and they're able to communicate with each other, without having to resort to incognito mode. That leads me to think the problem is _somewhere_ in this module, or in `simple-peer`.

**Comment by perguth** [comment]
I will certainly stay subscribed :)

**Comment by G-Ray** [comment]
Any update on this ?

**Comment by mckeown12** [comment]
Any update on this?

**Comment by mreinstein** [comment]
I haven't taken time to explore this, and it's been too long; I'm no longer familiar with the internals of these webrtc modules.

I still suspect the limitation is somewhere in `webrtc-swarm` or `signalhub`;  I don't know of any webrtc limitation in the spec that prevents having more than 2 connections per browser/host.
