### ISSUE TITLE
tests hang and don't complete

### ISSUE THREAD

**Issue by mreinstein** [mafintosh/webrtc-swarm#19]
repro steps:

``` bash
git clone https://github.com/mafintosh/webrtc-swarm.git
cd webrtc-swarm
npm i
npm test
```

console output:

``` bash
> webrtc-swarm@2.8.0 test /Users/mike/webrtc-swarm
> standard && tape test.js

TAP version 13
# greet and close

```

the tests don't progress any further and hang here indefinitely.

On a related note, it might make sense to locally run a hub instance rather than relying on `https://signalhub.mafintosh.com`. It would make the tests more isolated and reduce traffic to your public endpoint as well.

**Comment by perguth** [comment]
It hangs because the two swarm instances don't have matching ["appName" namespaces](https://github.com/mafintosh/signalhub#hub--signalhubappname-urls) and thus never see each other ([code lines](https://github.com/mafintosh/webrtc-swarm/blob/master/test.js#L10)).
