### ISSUE TITLE
Initial broadcast doesn't fire in browser

### ISSUE THREAD

**Issue by uiur** [mafintosh/webrtc-swarm#2]
I'm using this module with browserify in Chrome latest.
I tried the example, but it didn't work.

I've found `'open'` event doesn't fire from `hub.subscribe(me)`, so `connect()` doesn't trigger.

``` js
hub.subscribe(me).once('open', connect).pipe(through.obj(function (data, enc, cb) {
```

https://github.com/mafintosh/webrtc-swarm/blob/master/index.js#L77

My current workaround is just use `setTimeout`.

``` js
setTimeout(connect, 0)

hub.subscribe(me).pipe(through.obj(function (data, enc, cb) {
```

Do you have any idea about this issue?

**Comment by mafintosh** [comment]
Try trying again with the latest version of signalhub (4.1.1) which fixes some bugs that might be related to this.

**Comment by uiur** [comment]
It works! Thanks :)

**Comment by mafintosh** [comment]
\o/
