### ISSUE TITLE
configuration of the signal server?

### ISSUE THREAD

**Issue by didlie** [mafintosh/webrtc-swarm#40]
Are there any configuration requirements for the signal server? Is this compatible with simple peer? When I use the signal server from a browser I do not see the standard SDP that I expect for WebRTC!!!

**Comment by perguth** [comment]
Did you read through the readmes of the submodules already?

**Comment by didlie** [comment]
yes...no clear client level api. it is written like the docker image pre-configures everything; and I assume it does. But then where is the api for getting and giving peer details? example: do I access the singalserver using a URL scheme like "?room=some_room" or a subdirectory query like "{signalserver}/this_is_my_room_name"? ...or is it something completely different? please explain.

**Comment by perguth** [comment]
There is no Docker image in this stack. Signalhub is for relaying signaling messages from simple-peer. Regarding the scheme you can take a look here: https://github.com/mafintosh/signalhub/blob/master/index.js#L110

**Comment by didlie** [comment]
Thanks
