### ISSUE TITLE
does not appear to be working.

### ISSUE THREAD

**Issue by piedshag** [mafintosh/webrtc-swarm#5]
Using the following code in the browser webrtc-swarm does not appear to be able to create more than two connections. If i refresh two tabs at exactly the same time they will connect but when i try and connect more they simply seem to be ignored. All clients are subscribing to the hub but the first two only seem to be able to make a connection. Have you had this working recently. Thanks.

``` js
var signalhub = require('signalhub')
var swarm = require('webrtc-swarm')

var hub = signalhub('myapp', [
  'http://localhost:8080'
])

var sw = swarm(hub)

sw.on('peer', function (peer) {
    console.log(peer)
})
```

**Comment by max-mapper** [comment]
looking into this now

**Comment by max-mapper** [comment]
I fixed the example :D
